### ISSUE TITLE
Reverse / map / filter / reduce / every / some

### ISSUE THREAD

**Issue by dcousens** [feross/buffer#130]
`Buffer.prototype.[reverse / map / filter / reduce / every / some]` exists in node `v6.3.1`,  implementation could be grabbed directly from https://github.com/crypto-browserify/buffer-reverse

**Comment by fanatid** [comment]
`Buffer.prototype.reverse` only needed for object implementation. Except `reverse` object implementation also doesn't have `map` / `filter` / `reduce` / etc..

**Comment by feross** [comment]
I don't think it's reasonable or important to support these methods in browsers that lack typed array support.

Usage of `reverse` / `map` / `filter` / `reduce` / `every` / `some` in real-world npm packages is likely low or non-existant because:

1. These methods are [not documented](https://nodejs.org/api/buffer.html) in the Node.js docs
2. There are zero tests that uses these methods in the buffer test suite.
3. `Buffer.prototype.map` doesn't even work correctly in Node v4, so no reasonable packages will use it while Node v4 is in LTS. Example:

  ```js
  B.from('abc').map(function (letter) { console.log(letter) })
  // Throws "TypeError: this is not a typed array."
  ```

Even still, folks are free to use these methods in their browser code and they'll work in browsers that support typed arrays and array subclassing. But I really have no interest in shipping implementations of `map`, `filter`, etc. just to support this edge case.

Feel free to continue discussion if you disagree, but I'm going to close this.

**Comment by dcousens** [comment]
> By the time that Node v4 is out of LTS and folks actually start using these methods, this won't be an issue anymore.

Is that to say it will be implemented in the future?

**Comment by feross** [comment]
They're already implemented. The methods are inherited from the superclass `TypedArray.prototype`. But they only work correctly in browsers that support typed arrays and Array subclassing. Today, that's the latest versions of Chrome/Opera, Firefox, Edge, and Safari (technology preview).
