### ISSUE TITLE
compatibility issue of standalone bundle in jsfiddle

### ISSUE THREAD

**Issue by smcatala** [feross/buffer#151]
strangely enough, the example from the Node documentation for [Buffer.from(string, [encoding])](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding)
does not seem to work in jsfiddle when using the [standalone bundle](https://wzrd.in/standalone/buffer):
https://jsfiddle.net/2szjx8zp/ (tested in Chrome and Firefox)

the example can be made to work by replacing `Buffer.from()` calls with `new Buffer()`, the latter being the deprecated predecessor of the former.

for some reason, the static 'from' method of the Buffer class seems to be that of the underlying [TypedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from), which is not equivalent to that of Node's Buffer.

**Comment by feross** [comment]
It looks like the version of buffer served by https://wzrd.in/standalone/buffer is v4.x, not v5.x. I suspect this is because browserify is still bundling v4.x of this package. I'll get that updated soon.

If you test with the latest version of the code in this repo, you'll see that your code sample works just fine.
