### ISSUE TITLE
Ends up in production build :-S

### ISSUE THREAD

**Issue by davscro** [feross/buffer#161]
Hi all,

could someone explain me why this package ends up in production build. Am I missing something?

<img width="677" alt="screen shot 2017-05-13 at 00 43 56" src="https://cloud.githubusercontent.com/assets/1383250/26019395/4e35cef4-3775-11e7-91ff-f4add91f410d.png">

```yarn why buffer```

<img width="538" alt="screen shot 2017-05-13 at 00 45 25" src="https://cloud.githubusercontent.com/assets/1383250/26019467/b8e25862-3775-11e7-8785-5fcfe0d7d81b.png">

```yarn why node-libs-browser```
<img width="444" alt="screen shot 2017-05-13 at 00 45 57" src="https://cloud.githubusercontent.com/assets/1383250/26019479/cea28f14-3775-11e7-9fbe-916ce2976fb1.png">

And webpack is specified only as dev dependency.

Thanks in advance,
Davor

**Comment by dcousens** [comment]
I suspect this might be a question for webpack, not this module.

**Comment by davscro** [comment]
Ok, thanks for your feedback... 
Best,
Davor

**Comment by feross** [comment]
If any of the modules that you use (directly or indirectly) in your bundle refer to the `Buffer` global or do `require('buffer')`, then this package will be included. This is because `Buffer` is not defined in the browser, only Node.js, but some packages on npm assume that it exists. To ensure that these packages can work in the browser, your bundler will include this package to "polyfill" support for Buffer.

**Comment by davscro** [comment]
hi @feross 
thanks for your answer...I already found why this module endsup in production build. Take a look at https://github.com/mzabriskie/axios/issues/901
