### ISSUE TITLE
startsWith(" ") returns false in react-native while it should return true.

### ISSUE THREAD

**Issue by searene** [feross/buffer#216]
I'm using react-native, and there is a weird phenomenon when using this library in it. Please see the steps below to reproduce it.

### Steps to reproduce
First create a react-native project and install `buffer` as a dependency.
```bash
create-react-native-app react-app-project
cd react-app-project
yarn add buffer
```

Then add the following lines in `App.js`:

```js
import { Buffer } from "buffer";

export default class App extends React.Component {
  async componentDidMount() {
    const buffer = Buffer.from("2054", "hex");
    const s = buffer.toString("utf8");
    console.log(s); // s = " T"
    console.log(s.startsWith(" ")); // it will print false!
  }
  ......
}
```

Run the following command to open the dev menu on your device.

```bash
sudo adb shell input keyevent KEYCODE_MENU
```

Make sure you are not debugging it remotely(Because it works correctly when remote debugging is enabled). Anyway, make it look like the following image.

<img width="188" alt="deepinscreenshot_select-area_20180819161730" src="https://user-images.githubusercontent.com/3351317/44306928-76b40d00-a3cb-11e8-9021-947d10631a00.png">

Then run the application.

```bash
yarn start
```

Open `Expo` on your device, and start the app in it. Then you will see that `false` is printed on your computer screen.

```bash
16:15:59:  T
16:15:59: false
```

But it should be `true`! Because the first character IS space! 
By the way, the issue only occurs in react-native.

**Comment by feross** [comment]
Running your code directly in the Node.js terminal works fine for me:

```js
var B = require('buffer/').Buffer
const buffer = B.from("2054", "hex")
const s = buffer.toString("utf8");
console.log(s); // s = " T"
console.log(s.startsWith(" ")); // Prints true!
```

One thing that I noticed you did wrong is you used `require('buffer')` instead of `require('buffer/')`. The latter is required to tell Node to use the npm package and not the built-in buffer package.

In the react-native context, I'm not sure what `require('buffer')` does, but my guess is that it will pull in an older version of the `buffer` package which perhaps has a bug.

I'm closing this issue since there's no bug to fix here, but feel free to continue discussion! ✨
