### ISSUE TITLE
crypto.getRandomValues and Buffer throws a TypeError on Safari iOS 7

### ISSUE THREAD

**Issue by mpfluger** [feross/buffer#63]
When using https://github.com/crypto-browserify/randombytes on Safari iOS 7 it throws a TypeError.

This works:

    var a = new Uint8Array(128)
    crypto.getRandomValues(a)

This throws a TypeError with message `"Type error"`:

    var b = Buffer(128)
    crypto.getRandomValues(b)

The second case is how `randombytes` implements it, see https://github.com/crypto-browserify/randombytes/blob/master/browser.js#L17-21.

The current implementation works fine on Safari iOS 8.x, so this seems to be a bug in Safari iOS 7.

Just for fun I forked `randombytes` and changed it to using Uint8Array and then converting to a Buffer:
https://github.com/mpfluger/randombytes/commit/711ccbc7274bf60e4e0f0e6071ca8a5a1a6cc1f9

I'm not sure if that's a workable solution or if there is something in the `buffer` project you can do to handle that correctly.

**Comment by mpfluger** [comment]
Just for reference on iOS 7 Safari reports `navigator.userAgent` as `"Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D167"`

**Comment by dcousens** [comment]
@mpfluger it seems this is a `Buffer` problem,  AFAIK `Buffer` should be synonymous with `Uint8Array` if everything works out.

@feross ?

**Comment by feross** [comment]
This is happening because Safari 7 gets the buffer implementation based on `Object`, not `Uint8Array`. This started happening with these two commits from a PR: https://github.com/feross/buffer/commit/364ab7048f512e582868d40a17020ce2405586c3 and https://github.com/feross/buffer/commit/57f423901b998b61a77ec5d65c1ce2cfcd554695 by @parshap.

The change detects whether the browser supports changing the `constructor` property of an object instance, which buffer does in order to enable [`is-buffer`](https://github.com/feross/is-buffer) to detect buffers without needing to `require('buffer')`. You can see the code here: https://github.com/feross/buffer/blob/c447c977d1429de896806dba7ae543612e5da992/index.js#L49

Since Safari 7's implementation is broken, the actual `Buffer` class is returned from the `Buffer` constructor instead of a `Uint8Array`, which means that the `constructor` property will be set correctly for `is-buffer` to detect.

Workarounds:

- Use an older version of `buffer`, 3.3.0.
- Set `Buffer.TYPED_ARRAY_SUPPORT = true` in Safari 7 to force it to always use typed arrays.
- Test if the Buffer is a typed array before using it with `crypto` methods. `buffer instanceof Uint8Array`

Possible solution:

- Change `is-buffer` to detect buffers using the private `_isBuffer` property that we set on the buffers we create, and then we can dispense with setting the constructor.

I'm hesitant to make any change at all though, since Safari 7 is broken and the Buffer we return works just fine. It's just not a `Uint8Array`. Safari 7 marketshare is 0.83% and shrinking.

Thoughts?

**Comment by feross** [comment]
@mpfluger 

The solution in your fork looks fine, but you can make it more efficient by avoiding the Buffer constructor which does a copy. Use [`typedarray-to-buffer`](https://www.npmjs.com/package/typedarray-to-buffer) instead of the Buffer constructor and the Uint8Array will be re-used when possible.

Change:

```
var out = new Buffer(bytes)
```

To:

```
var toBuffer = require('typedarray-to-buffer')
...
var out = new toBuffer(bytes)
```

**Comment by mpfluger** [comment]
@feross 

Thanks a lot for you feedback. I understand your sentiment of not wanting to deploy a strange fix for a dying browser. I did some more research and this affects all Safari browsers before version 8. Still a pretty small market share, but maybe worth a fix - it's up to you.

On our end I will use your proposition from above: `Buffer.TYPED_ARRAY_SUPPORT = true`.

Just for reference, here's the implementation we are using. It's not great, but it works on all versions we have tried:

    // This fixes a bug with Safari < 8 and the Browserify Buffer shim used in Crypto-browserify/randombytes
    // See: https://github.com/feross/buffer/issues/63
    if (navigator && navigator.vendor &&
        navigator.vendor.indexOf('Apple') > -1) {
        var versionStart = navigator.userAgent.toLowerCase().indexOf('applewebkit') + 12;
        var version = navigator.userAgent.substr(versionStart, 1);
        
        if (version && typeof(parseInt(version)) === 'number' && parseInt(version) < 6) {
            Buffer.TYPED_ARRAY_SUPPORT = true;
        }
    }

I'll leave it up to you if want to close the Issue.

Thanks again for your help!

**Comment by feross** [comment]
@mpfluger Thanks for understanding! I'll close this issue since you found a suitable workaround :)

**Comment by mpfluger** [comment]
@feross Thanks again for explaining this in detail and providing a solution!

**Comment by feross** [comment]
Happy to :+1:
